// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.ReadingTimeCalculator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("text_length")]
        public long TextLength { get; set; }

        [JsonProperty("word_count")]
        public long WordCount { get; set; }

        [JsonProperty("reading_time_minutes")]
        public long ReadingTimeMinutes { get; set; }

        [JsonProperty("reading_time_seconds")]
        public long ReadingTimeSeconds { get; set; }

        [JsonProperty("reading_time_text")]
        public string ReadingTimeText { get; set; }

        [JsonProperty("words_per_minute")]
        public long WordsPerMinute { get; set; }
    }
}
